### ISSUE TITLE
OCaml 4.10 + ppx_string 0.14.0 - "src/ppx_string.ml", line 98, characters 6-32:Error: Unbound module Stdio

### ISSUE THREAD

**Issue by XVilka** [janestreet/ppx_string#2] opened 2020-08-28 04:54 UTC
After an recent update to ppxlib.0.15.0 rebuilt all ppx packages, and ppx_string failed with the following error:
```
><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[ERROR] The compilation of ppx_string failed at "/home/akochkov/.opam/opam-init/hooks/sandbox.sh build dune build -p ppx_string -j 7".
∗ installed splittable_random.v0.14.0
∗ installed ppx_expect.v0.14.0
∗ installed base_quickcheck.v0.14.0

#=== ERROR while compiling ppx_string.v0.14.0 =================================#
# context     2.0.7 | linux/x86_64 | ocaml-system.4.10.0 | https://opam.ocaml.org/#2010b207
# path        ~/.opam/ocaml-system/.opam-switch/build/ppx_string.v0.14.0
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build -p ppx_string -j 7
# exit-code   1
# env-file    ~/.opam/log/ppx_string-2620755-af3201.env
# output-file ~/.opam/log/ppx_string-2620755-af3201.out
### output ###
# [...]
# File "src/ppx_string.ml", line 98, characters 6-32:
# 98 |       Stdio.In_channel.with_file loc.loc_start.pos_fname ~f:(fun ic ->
#            ^^^^^^^^^^^^^^^^^^^^^^^^^^
# Error: Unbound module Stdio
# Hint: Did you mean Stdlib?
#     ocamlopt src/.ppx_string.objs/native/ppx_string.{cmx,o} (exit 2)
# (cd _build/default && /usr/bin/ocamlopt.opt -w -40 -g -I src/.ppx_string.objs/byte -I src/.ppx_string.objs/native -I /home/akochkov/.opam/ocaml-system/lib/base -I /home/akochkov/.opam/ocaml-system/lib/base/base_internalhash_types -I /home/akochkov/.opam/ocaml-system/lib/base/caml -I /home/akochkov/.opam/ocaml-system/lib/base/shadow_stdlib -I /home/akochkov/.opam/ocaml-system/lib/ocaml-compile[...]
# File "src/ppx_string.ml", line 98, characters 6-32:
# 98 |       Stdio.In_channel.with_file loc.loc_start.pos_fname ~f:(fun ic ->
#            ^^^^^^^^^^^^^^^^^^^^^^^^^^
# Error: Unbound module Stdio
# Hint: Did you mean Stdlib?
```

**Comment by MinorProphet** [comment] 2020-08-28 07:06
I think I hit this as well.  It is my first time downloading/using opam/ocaml.  I encountered the following error while trying to install core for the first time (right after base and utop).

```
$ opam --version
2.0.7
```

```
$ opam switch
#  switch   compiler                    description
→  default  ocaml-base-compiler.4.11.0  default
```

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:    20.04
```

```
$ opam install core

[ERROR] The compilation of ppx_string failed at "$HOME/.opam/opam-init/hooks/sandbox.sh build dune build -p
        ppx_string -j 7".

#=== ERROR while compiling ppx_string.v0.14.0 =================================#
# context     2.0.7 | linux/x86_64 | ocaml-base-compiler.4.11.0 | https://opam.ocaml.org#2010b207
# path        ~/.opam/default/.opam-switch/build/ppx_string.v0.14.0
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build -p ppx_string -j 7
# exit-code   1
# env-file    ~/.opam/log/ppx_string-1438380-df7474.env
# output-file ~/.opam/log/ppx_string-1438380-df7474.out
### output ###
# [...]
# File "src/ppx_string.ml", line 98, characters 6-32:
# 98 |       Stdio.In_channel.with_file loc.loc_start.pos_fname ~f:(fun ic ->
#            ^^^^^^^^^^^^^^^^^^^^^^^^^^
# Error: Unbound module Stdio
# Hint: Did you mean Stdlib?
#     ocamlopt src/.ppx_string.objs/native/ppx_string.{cmx,o} (exit 2)
# (cd _build/default && $HOME/.opam/default/bin/ocamlopt.opt -w -40 -g -I src/.ppx_string.objs/byte -I src/.ppx_string.objs/native -I $HOME/.opam/default/lib/base -I $HOME/.opam/default/lib/base/base_internalhash_types -I $HOME/.opam/default/lib/base/caml -I $HOME/.opam/default/lib/base/shadow_stdlib -I $HOME/.opam/default/lib/ocaml-co[...]
# File "src/ppx_string.ml", line 98, characters 6-32:
# 98 |       Stdio.In_channel.with_file loc.loc_start.pos_fname ~f:(fun ic ->
#            ^^^^^^^^^^^^^^^^^^^^^^^^^^
# Error: Unbound module Stdio
# Hint: Did you mean Stdlib?

Error report
┌─ The following actions failed
│ &lambda; build ppx_string v0.14.0
```

**Comment by MattWindsor91** [comment] 2020-08-28 09:40
I _think_ this is fixable as follows (ie, literally adding `stdio` in as an explicit dependency):

```diff
diff --git a/ppx_string.opam b/ppx_string.opam
index 74bdaf7..04889bc 100644
--- a/ppx_string.opam
+++ b/ppx_string.opam
@@ -13,6 +13,7 @@ build: [
 depends: [
   "ocaml"    {>= "4.04.2"}
   "base"     {>= "v0.14" & < "v0.15"}
+  "stdio"    {>= "v0.14" & < "v0.15"}
   "ppx_base" {>= "v0.14" & < "v0.15"}
   "dune"     {>= "2.0.0"}
   "ppxlib"   {>= "0.11.0"}
diff --git a/src/dune b/src/dune
index 39f0e99..4ed24de 100644
--- a/src/dune
+++ b/src/dune
--- a/src/dune
+++ b/src/dune
@@ -1,4 +1,4 @@
 (library (name ppx_string) (public_name ppx_string) (kind ppx_rewriter)
- (libraries base compiler-libs.common ppxlib)
+ (libraries base stdio compiler-libs.common ppxlib)
  (preprocess
   (pps ppx_base -annotated-ignores ppxlib.metaquot ppxlib.traverse)))
\ No newline at end of file
```

~I presume Jane Street doesn't directly accept pull requests (given the way that commits seem to mirror another repo?), so I haven't opened one.~  just read `CONTRIBUTING`, I could open a prq but I presume it'd end up targeting 0.15 instead of 0.14?

**Comment by XVilka** [comment] 2020-08-28 09:58
Probably just a patch release.
cc @xclerc

**Comment by neojski** [comment] 2020-08-29 00:18
I had the same problem and @MattWindsor91's patch does fix it. You can temporarily fix your build by cloning the branch in #3  and pinning your ppx_string to it with: `opam pin ppx_string  .`

**Comment by copy** [comment] 2020-08-29 20:25
This is already fixed in master (you should check the closed issues before reporting a new one: https://github.com/janestreet/ppx_string/issues/1)

**Comment by na4zagin3** [comment] 2020-08-30 08:34
Why not backporting the patch to v0.14.0 (https://github.com/ocaml/opam-repository/tree/master/packages/ppx_string/ppx_string.v0.14.0) not only fixing master?

**Comment by XVilka** [comment] 2020-08-31 04:52
Yes, currently it is unusable as is in 0.14.0 version.

**Comment by hcnelson99** [comment] 2020-08-31 15:22
For a less fragile workaround, you can run `opam pin add ppx_string git://github.com/janestreet/ppx_string\#d498c52ffc00506aaa8155a7aee5b9fc1e22d4be`

It would be amazing if this could get backported to v0.14!

**Comment by leviroth** [comment] 2020-08-31 15:41
I believe this is fixed via an opam repository change and this issue can be closed: https://github.com/ocaml/opam-repository/pull/17091

My GitHub Actions jobs are working now, so it looks like this has hit the repository cache.

**Comment by hcnelson99** [comment] 2020-08-31 16:10
I can confirm that this is fixed. Thanks so much @kit-ty-kate and I hope you enjoyed your vacation!

**Closed as completed** 2020-09-02 15:51 UTC
Labels: forwarded-to-js-devs
